blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/4Source/obsidian-plugin-template/discussions/new/choose
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/4Source/obsidian-plugin-template/wiki
    about: Check out the documentation if you want to know what's possible.
  - name: Contributing
    url: https://github.com/4Source/obsidian-plugin-template/blob/master/.github/CONTRIBUTING.md
    about: Overview of the contribution workflow
